spring:
  application:
    name: kolo-backend

  datasource:
    url: jdbc:postgresql://localhost:5433/kolo_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  data:
    redis:
      host: localhost
      port: 6380
      timeout: 2000ms

  task:
    execution:
      pool:
        core-size: 5
        max-size: 20

jwt:
  secret: dev-secret-key-minimum-256-bits-long-change-in-production-never-use-this
  access-token-expiry: 86400000
  refresh-token-expiry: 604800000

paystack:
  secret-key: ${PAYSTACK_SECRET_KEY:sk_test_34e7df8065fb09e507319eb3bc3fbb4911bd7e0e}
  base-url: https://api.paystack.co

termii:
  api-key: ${TERMII_API_KEY:TLwjtWUcDMpSrDzPegOZzSFvQExKbwkwahNqKHsKfJDSjCptcfRpTZClMZMRNk}
  base-url: ${TERMII_BASE_URL:https://v3.api.termii.com}

smile:
  api-key: your_smile_key
  partner-id: your_partner_id
  base-url: https://api.smileidentity.com

otp:
  expiry-minutes: 10
  length: 6

kolo:
  fine:
    grace-period-days: 3
    tier-one-rate: 0.05
    tier-two-rate: 0.10
    platform-cut: 0.30
  loan:
    tier-one-interest-rate: 0.05
    tier-two-interest-rate: 0.10
    platform-interest-cut: 0.30
    voting-window-hours: 72

server:
  port: 8080

logging:
  level:
    com.kolo: DEBUG
    org.springframework.security: DEBUG